services:
  jellytelegram-sync:
    image: drumsergio/jellytelegram-sync:0.0.1
    container_name: jellytelegram-sync
    environment:
      # Telegram variables
      - TELEGRAM_API_ID=your_telegram_api_id
      - TELEGRAM_API_HASH=your_telegram_api_hash
      - TELEGRAM_CHANNEL=username_or_channel_id
      
      # Jellyfin variables
      - JELLYFIN_URL=http://your_jellyfin_url:8096
      - JELLYFIN_API_KEY=your_jellyfin_api_key
      
      # Script interval execution (in seconds). If you want it to run constantly, you would adjust the code accordingly (optional)
      - SCRIPT_INTERVAL=3600

    volumes:
      - /mnt/user/appdata/jellytelegram-sync:/app # users.csv and Telegram session

    restart: unless-stopped